# -*- coding: utf-8 -*-
"""reto1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1htKnezmOsOlvbDK5Dodt5HAf9rQu_n9a
"""

var_1 = int(input(("Ingrese su Presion Sistolica: ")))
var_2 = int(input(("Ingrese su Presion Diastolica: ")))
if ((var_1<90) & (var_2<70)):
  print("Hipotension Alerta Naranja")
elif ((90<=var_1<130) & (70<=var_2<90)):
  print("Optima Alerta Verde")
elif ((130<=var_1<140) & (90<=var_2<95)): 
  print("Normal Alerta Verde")
elif ((140<=var_1<150) & (95<=var_2<100)):
  print("Normal-alta Alerta Amarilla")
elif ((150<=var_1<170) & (100<=var_2<110)):
  print("HTA Grado 1 Alerta Naranja")
elif ((170<=var_1<190) & (110<=var_2<120)):
  print("HTA Grado 2 Alerta Roja")
elif ((var_1>=190) & (var_2>=120)):
  print("HTA Grado 3 Alerta Roja")
elif ((var_1>=150) & (var_2<100)):
  print("HTA Sistolica Aislada Alerta Naranja")
else:
  print("No se puede determinar la categoria Alerta Gris")