# -*- coding: utf-8 -*-
"""reto2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zWk5BHFj0sPnTFwxq12CgSPO34ILU5Ur
"""

"""reto2"""

cant_1 = int(input())#Ingresa cantidad de medicamento 1 existente
cant_2 = int(input())#Ingresa cantidad de medicamento 2 existente
a = cant_1
b = cant_2
pacientes, pacientes_1, pacientes_2 = 0, 0, 0

while (cant_1 > 0) and (cant_2 > 0):
  
  presion_sistolica = int(input())#Ingrese presion sistolica
  presion_diastolica = int(input())#Ingrese presion diastolica
  pacientes += 1

  if (presion_sistolica < 90) and (presion_diastolica < 70): #Medicamento 2 (Categoria: Hipotension)
    cant_2 -= 15
    pacientes_2 += 1
  elif (90 <= presion_sistolica < 130) and (70 <= presion_diastolica < 90): #Ningun Medicamento (Categoria: Optima)
    continue
  elif (130 <= presion_sistolica < 140) and (90 <= presion_diastolica < 95): #Ningun Medicamento (Categoria: Normal)
    continue
  elif (140 <= presion_sistolica < 150) and (95 <= presion_diastolica < 100): #Medicamento 1 (Categoria: Normal-alta)
    cant_1 -= 10
    pacientes_1 += 1
  elif (150 <= presion_sistolica < 170) and (100 <= presion_diastolica < 110): #Medicamento 1 (Categoria: HTA Grado 1)
    cant_1 -= 10
    pacientes_1 += 1
  elif (170 <= presion_sistolica < 190) and (110 <= presion_diastolica < 120): #Medicamento 1 (Categoria: HTA Grado 2)
    cant_1 -= 20
    pacientes_1 += 1
  elif (presion_sistolica >= 190) and (presion_diastolica >= 120): #Medicamento 1 (Categoria: HTA Grado 3)
    cant_1 -= 50
    pacientes_1 += 1
  elif (presion_sistolica >= 150) and (presion_diastolica < 100): #Medicamento 1 (Categoria: HTA Sitolica Aislada)
    cant_1 -= 20
    pacientes_1 += 1
  else: #Sin categoria
    continue
  porcentaje_1 = "{0:.2f}".format((pacientes_1/pacientes)*100) #la funcion format es para que me entrege dos cifras decimales
  porcentaje_2 = "{0:.2f}".format((pacientes_2/pacientes)*100)
  

if (cant_1 == a) and (cant_2 == b): #Compara si no se entregaron medicamentos, ambos deben ser iguales a su valor inicial
  pacientes, pacientes_1, pacientes_2 = 0, 0, 0
  porcentaje_1, porcentaje_2 = "{0:.2f}".format(0), "{0:.2f}".format(0) 
  
print(pacientes)
print(pacientes_1, porcentaje_1,"%")
print(pacientes_2, porcentaje_2,"%")